import {
  faCircleArrowRight,
  faBell,
  faMagnifyingGlass,
  faArrowRightLong,
  faTimes,
  faTags,
  faCommentDots,
  faFileInvoiceDollar,
  faUser,
  faHouseFire,
  faCaretDown,
  faFlag,
  faBoxOpen,
  faShoppingBag,
  faBox,
  faEarthAmericas,
  faDog,
  faComputer,
  faBroom,
  faArrowUpWideShort,
  faPersonShelter,
  faClock,
  faLocationCrosshairs,
  faBookBookmark,
  faArrowRight,
  faArrowLeftLong,
  faClockRotateLeft,
  faLocationDot,
  faCircleDollarToSlot,
  faPerson,
  faPeopleGroup,
} from '@fortawesome/free-solid-svg-icons';
import { fa500px } from '@fortawesome/free-brands-svg-icons';
import { faAddressCard } from '@fortawesome/free-regular-svg-icons';

export const NATIVE_ICONS = {
  faCircleArrowRight,
  faBell,
  faMagnifyingGlass,
  faArrowRightLong,
  faTimes,
  faTags,
  faCommentDots,
  faFileInvoiceDollar,
  faUser,
  faHouseFire,
  faCaretDown,
  faFlag,
  faBoxOpen,
  faShoppingBag,
  faBox,
  faEarthAmericas,
  faDog,
  faComputer,
  faBroom,
  faArrowUpWideShort,
  faPersonShelter,
  faClock,
  faLocationCrosshairs,
  faBookBookmark,
  faArrowRight,
  faArrowLeftLong,
  faClockRotateLeft,
  faLocationDot,
  faCircleDollarToSlot,
  faPerson,
  faPeopleGroup
};

export type nativeIconNameType = keyof typeof NATIVE_ICONS;
