import {
  faCircleArrowRight,
  faBell,
  faMagnifyingGlass,
  faArrowRightLong,
  faTimes,
  faTags,
  faComments as faCommentsSolid,
  faFileInvoiceDollar,
  faUser as faUserSolid,
  faHouseFire,
  faCaretDown,
  faFlag,
  faBoxOpen,
  faShoppingBag,
  faBox,
  faEarthAmericas,
  faDog,
  faComputer,
  faBroom,
  faPersonShelter,
  faClock,
  faLocationCrosshairs,
  faBookBookmark,
  faArrowRight,
  faArrowLeftLong,
  faClockRotateLeft,
  faLocationDot,
  faCircleDollarToSlot,
  faStar,
  faThumbsDown,
  faMoneyBills,
  faTruckFast,
  faHouseCircleCheck,
  faStreetView,
  faPeopleCarryBox,
  faCompass as faCompassSolid,
  faRectangleList as faRectangleListSolid,
  faSun as faSunSolid,
  faArrowUpZA,
  faPeopleGroup,
  faPerson,
  faStarHalfStroke,
  faGripLines,
  faPhone,
} from '@fortawesome/free-solid-svg-icons';
import { fa500px } from '@fortawesome/free-brands-svg-icons';
import {
  faComments as faCommentsRegular,
  faHeart,
  faUser as faUserRegular,
  faCompass as faCompassRegular,
  faRectangleList as faRectangleListRegular,
  faSun as faSunRegular,
  faStar as faStarEmptyStroke,
  faBell as faBellRegular,
} from '@fortawesome/free-regular-svg-icons';

export const NATIVE_ICONS = {
  faCircleArrowRight,
  faBell,
  faBellRegular,
  faMagnifyingGlass,
  faArrowRightLong,
  faTimes,
  faTags,
  faCommentsSolid,
  faCommentsRegular,
  faFileInvoiceDollar,
  faUserSolid,
  faUserRegular,
  faRectangleListSolid,
  faRectangleListRegular,
  faSunRegular,
  faSunSolid,
  faCompassSolid,
  faCompassRegular,
  faHouseFire,
  faCaretDown,
  faFlag,
  faBoxOpen,
  faShoppingBag,
  faBox,
  faEarthAmericas,
  faDog,
  faComputer,
  faBroom,
  faPersonShelter,
  faClock,
  faLocationCrosshairs,
  faBookBookmark,
  faArrowRight,
  faArrowLeftLong,
  faClockRotateLeft,
  faLocationDot,
  faCircleDollarToSlot,
  faStar,
  faHeart,
  faThumbsDown,
  faMoneyBills,
  faTruckFast,
  faHouseCircleCheck,
  faStreetView,
  faPeopleCarryBox,
  faArrowUpZA,
  faPeopleGroup,
  faPerson,
  faStarHalfStroke,
  faStarEmptyStroke,
  faGripLines,
  faPhone,
};

export type nativeIconNameType = keyof typeof NATIVE_ICONS;
