// import { generateSecureHash } from '../helper';

export const LOCAL_STORAGE_KEYS = {
  AD_REPORT: 'AD_REPORT_LOCAL',
  LOCATION_REPORT: 'LOCATION_REPORT_LOCAL',
  FORGOT_PSW_EMAIL: 'FPSWEMAIL',
  REGIONS: 'regions',
};
export const COOKIE_KEYS = {
  ACCESS_TOKEN: 'token',
  REFRESH_TOKEN: 'refresh_token',
  REGIONS: 'regions',
};
export enum QUERY_N_MUTATION_KEYS {
  GET_ALL_CATEGORIES,
  GET_ALL_SERVICES_OF_CATEGORY,
  GET_SERVICE_DETAIL,
  GET_MATCHING_ORDER_DETAIL,
  GET_ORDER_DETAIL,
  GET_FREELANCER_PREVIEW_DATA,
  GET_FREELANCER_DETAIL,
  GET_FREELANCER_INCOMING_ORDERS,
  GET_MARKETPLACE_ORDERS,
}
