export const OFFICER_PAGES = {
  AUTH: '/',
  RESET_PASSWORD: '/reset-password',
  RESET_PASSWORD_OTP: '/reset-password/otp',
  RESET_PASSWORD_NEW: '/reset-password/new',
  SOCIAL_AUTH: '/social-auth',
  DASHBOARD: '/dashboard',
  AD_LOCATION_DETAIL: '/ad-locations/detail',
  AD_LOCATION_EDIT: '/ad-locations/edit',
  ADS_LOCATION: '/ad-locations',
  ADS_BOARD: '/ad-boards',
  REPORT: '/reports',
  REQUEST_LIST: '/ad-requests',
  APPROVE_DETAIL: '/ad-requests/approve',
  MODIFICATION_DETAIL: '/ad-requests/modification',
  NEW_APPROVE: '/ad-requests/new',
  ME: '/me',
  PERSONAL_INFORMATION: '/me/personal-information',
  CHANGE_PASSWORD: '/me/change-password',
};
