export const BROADCAST_MESSAGE = {
  NEED_TOKEN: 'BM_NEED_TOKEN',
  SEND_TOKEN: 'BM_SEND_TOKEN',
  NEED_LOGOUT: 'BM_NEED_LOGOUT',
};
export const TOKEN_EXPIRY_DAYS = {
  NON_REMEMBER: 12,
  REMEMBER: 12,
};
export const BROADCAST_CHANNEL = {
  AUTH_CHANNEL: 'BC_AUTHENTICATION',
};
