version: '3.4'

networks:
  detoidockernetwork:
    driver: bridge

services:
  detoidb:
    container_name: detoi-server-database-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8004:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@12345#
    networks:
      - detoidockernetwork
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PPassword@12345#", "-Q", "select 1"]
      interval: 1s
      retries: 20

  detoiserver:
    container_name: detoi-server-container
    image: ${DOCKER_REGISTRY-}detoiserver
    build:
      context: .
      dockerfile: DeToiServer/Dockerfile
    ports:
      - 8000:8080
      - 8001:8081
    depends_on:
      detoidb:
        condition: service_healthy
    environment:
      - DB_HOST=detoidb
      - DB_NAME=DeToiVN
      - DB_SA_PASSWORD=Password@12345#
    env_file:
      - path: "./docker.env"
        required: true
    networks:
      - detoidockernetwork
